name: Daily Job

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "0 0 * * *"

jobs:
  generate-charts:
    name: Count Repos With At Least 1 Signed Artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Count 
        run: ./measure.sh mcr.microsoft.com --early-exit > results.txt

      - name: Git Add Changes
        run: git add -A

      - name: Git Commit Changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Add count results.txt"

      - name: Git Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          force_with_lease: true
